version: "3.8"

services:

  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy    
    environment:
      - WG_HOST=midominio.duckdns.org     # Change this to your host's public address  
      - PASSWORD=p4ssw0rd                 # Change this
    volumes:
      - ./wg-easy:/etc/wireguard          
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

